export const ADD_TODO = "ADD_TODO";
export const DELETE_TODO = "DELETE_TODO";
export const TOGGLE_TODO = "TOGGLE_TODO";
export const EDIT_TODO = "EDIT_TODO";
export const CLEAR_CHECKED = 'CLEAR_CHECKED';
export const HOVER_OVER = "HOVER_OVER";
export const LOAD_LOCALSTORAGE = "LOAD_LOCALSTORAGE";
export const SAVE_LOCALSTORAGE = "SAVE_LOCALSTORAGE";